name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"

categories:
  - title: "Features"
    labels:
      - "feat"
      - "feature"
  - title: "Fixes"
    labels:
      - "fix"
      - "bugfix"
  - title: "Chores"
    labels:
      - "chore"
      - "refactor"
      - "docs"

exclude-labels:
  - "skip-changelog"
