#!/usr/bin/env bash
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$PROJECT_ROOT"

echo "=== StackLift Setup (by Statix) ==="

# 1. Check Docker
if ! command -v docker &> /dev/null; then
    echo "Error: Docker is not installed or not in PATH."
    exit 1
fi

if ! docker info &> /dev/null; then
    echo "Error: Docker daemon is not running."
    exit 1
fi

if ! command -v docker compose &> /dev/null && ! command -v docker-compose &> /dev/null; then
    echo "Error: Docker Compose is not installed."
    exit 1
fi

echo "  Docker: OK"

# Ensure stacklift.config.env exists
if [ ! -f "stacklift.config.env" ]; then
    if [ -f "stacklift.config.env.example" ]; then
        cp stacklift.config.env.example stacklift.config.env
        echo "  Created stacklift.config.env from stacklift.config.env.example"
    else
        echo "Error: stacklift.config.env.example not found."
        exit 1
    fi
else
    echo "  stacklift.config.env: OK"
fi

# Load config and generate .env
source stacklift.config.env 2>/dev/null || true

# Build derived values
DATABASE_URL="postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@postgres:5432/${POSTGRES_DB:-stacklift}"
REDIS_URL="redis://redis:6379"
NEXT_PUBLIC_API_URL="http://localhost:${BACKEND_PORT:-3001}"
PGADMIN_URL="http://localhost:${PGADMIN_PORT:-5050}"
REDISINSIGHT_URL="http://localhost:${REDISINSIGHT_PORT:-5540}"

# Write .env
cat > .env << EOF
# Generated by setup script - do not edit manually
PROJECT_NAME=${PROJECT_NAME:-StackLift}
FRONTEND_PORT=${FRONTEND_PORT:-3000}
BACKEND_PORT=${BACKEND_PORT:-3001}
POSTGRES_PORT=${POSTGRES_PORT:-5432}
REDIS_PORT=${REDIS_PORT:-6379}
PGADMIN_PORT=${PGADMIN_PORT:-5050}
REDISINSIGHT_PORT=${REDISINSIGHT_PORT:-5540}
POSTGRES_USER=${POSTGRES_USER:-postgres}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
POSTGRES_DB=${POSTGRES_DB:-stacklift}
PGADMIN_EMAIL=${PGADMIN_EMAIL:-admin@stacklift.dev}
PGADMIN_PASSWORD=${PGADMIN_PASSWORD:-admin}
DATABASE_URL=$DATABASE_URL
REDIS_URL=$REDIS_URL
NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
LOG_LEVEL=${LOG_LEVEL:-info}
PGADMIN_URL=$PGADMIN_URL
REDISINSIGHT_URL=$REDISINSIGHT_URL
EOF

echo "  Generated .env"

# Generate pgpass for pgAdmin
PGPASS_FILE="config/pgadmin/pgpass"
mkdir -p "$(dirname "$PGPASS_FILE")"
echo "postgres:5432:*:${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}" > "$PGPASS_FILE"
echo "  Generated $PGPASS_FILE"

# Check port conflicts (optional)
check_port() {
    local port=$1
    if command -v lsof &> /dev/null; then
        if lsof -i ":$port" &> /dev/null; then
            echo "  Warning: Port $port may be in use"
        fi
    fi
}

check_port "${FRONTEND_PORT:-3000}"
check_port "${BACKEND_PORT:-3001}"
check_port "${POSTGRES_PORT:-5432}"

# Done
COMPOSE_CMD="docker compose"
if command -v docker-compose &> /dev/null && ! docker compose version &> /dev/null; then
    COMPOSE_CMD="docker-compose"
fi

echo ""
echo "=== Setup complete ==="
echo ""
echo "Start with:"
echo "  $COMPOSE_CMD up"
echo ""
echo "Or run in background:"
echo "  $COMPOSE_CMD up -d"
echo ""
