@echo off
setlocal EnableDelayedExpansion
cd /d "%~dp0\.."

echo === StackLift Setup (by Statix) ===

REM Check Docker
docker info >nul 2>&1
if errorlevel 1 (
    echo Error: Docker is not running or not in PATH.
    exit /b 1
)
echo   Docker: OK

docker compose version >nul 2>&1
if errorlevel 1 (
    docker-compose --version >nul 2>&1
    if errorlevel 1 (
        echo Error: Docker Compose not found.
        exit /b 1
    )
)

REM Ensure stacklift.config.env exists
if not exist "stacklift.config.env" (
    if exist "stacklift.config.env.example" (
        copy "stacklift.config.env.example" "stacklift.config.env" >nul
        echo   Created stacklift.config.env from example
    ) else (
        echo Error: stacklift.config.env.example not found.
        exit /b 1
    )
) else (
    echo   stacklift.config.env: OK
)

REM Load config (set defaults first, then override from file)
set "PROJECT_NAME=StackLift"
set "FRONTEND_PORT=3000"
set "BACKEND_PORT=3001"
set "POSTGRES_PORT=5432"
set "REDIS_PORT=6379"
set "PGADMIN_PORT=5050"
set "REDISINSIGHT_PORT=5540"
set "POSTGRES_USER=postgres"
set "POSTGRES_PASSWORD=postgres"
set "POSTGRES_DB=stacklift"
set "PGADMIN_EMAIL=admin@stacklift.dev"
set "PGADMIN_PASSWORD=admin"
set "LOG_LEVEL=info"

for /f "usebackq eol=# tokens=1,* delims==" %%a in ("stacklift.config.env") do (
    if not "%%a"=="" set "%%a=%%b"
)

REM Build derived values
set "DATABASE_URL=postgresql://%POSTGRES_USER%:%POSTGRES_PASSWORD%@postgres:5432/%POSTGRES_DB%"
set "REDIS_URL=redis://redis:6379"
set "NEXT_PUBLIC_API_URL=http://localhost:%BACKEND_PORT%"
set "PGADMIN_URL=http://localhost:%PGADMIN_PORT%"
set "REDISINSIGHT_URL=http://localhost:%REDISINSIGHT_PORT%"

REM Write .env
(
echo # Generated by setup script - do not edit manually
echo PROJECT_NAME=%PROJECT_NAME%
echo FRONTEND_PORT=%FRONTEND_PORT%
echo BACKEND_PORT=%BACKEND_PORT%
echo POSTGRES_PORT=%POSTGRES_PORT%
echo REDIS_PORT=%REDIS_PORT%
echo PGADMIN_PORT=%PGADMIN_PORT%
echo REDISINSIGHT_PORT=%REDISINSIGHT_PORT%
echo POSTGRES_USER=%POSTGRES_USER%
echo POSTGRES_PASSWORD=%POSTGRES_PASSWORD%
echo POSTGRES_DB=%POSTGRES_DB%
echo PGADMIN_EMAIL=%PGADMIN_EMAIL%
echo PGADMIN_PASSWORD=%PGADMIN_PASSWORD%
echo DATABASE_URL=%DATABASE_URL%
echo REDIS_URL=%REDIS_URL%
echo NEXT_PUBLIC_API_URL=%NEXT_PUBLIC_API_URL%
echo LOG_LEVEL=%LOG_LEVEL%
echo PGADMIN_URL=%PGADMIN_URL%
echo REDISINSIGHT_URL=%REDISINSIGHT_URL%
) > .env
echo   Generated .env

REM Generate pgpass
if not exist "config\pgadmin" mkdir "config\pgadmin"
(echo postgres:5432:*:%POSTGRES_USER%:%POSTGRES_PASSWORD%)> config\pgadmin\pgpass
echo   Generated config\pgadmin\pgpass

REM Optional port check (netstat)
netstat -an | findstr ":%FRONTEND_PORT% " >nul 2>&1
if not errorlevel 1 echo   Warning: Port %FRONTEND_PORT% may be in use
netstat -an | findstr ":%BACKEND_PORT% " >nul 2>&1
if not errorlevel 1 echo   Warning: Port %BACKEND_PORT% may be in use

echo.
echo === Setup complete ===
echo.
echo Start with:
echo   docker compose up
echo.
echo Or run in background:
echo   docker compose up -d
echo.
endlocal
